var SEARCH_INDEX=[
  {f:'kabal-sefirot.html',t:'Les 10 Sefirot',d:'Les dix canaux de la Lumière divine — Keter, Chokhmah, Binah, Chesed, Gevurah, Tiferet, Netzach, Hod, Yesod, Malkhut. Arbre de Vie, Etz Chaïm.',k:'sefirot keter chokhmah binah chesed gevurah tiferet netzach hod yesod malkhut arbre de vie etz chaim'},
  {f:'kabal-lettres.html',t:'Les 22 Lettres Hébraïques',d:'Aleph, Beth, Gimel — les lettres sacrées et leur pouvoir symbolique dans la Kabbale.',k:'lettres hebraiques aleph beth gimel alphabet sacre guematria kabbalah'},
  {f:'kabal-psaumes.html',t:'Psaumes Kabbalistiques',d:'Les psaumes et leur dimension kabbalistique, protection et élévation spirituelle.',k:'psaumes tehilim kabbale protection priere'},
  {f:'kabal-ein-sof.html',t:'Ein Sof — Lumière Infinie',d:'Ein Sof, la lumière sans fin, source de toute existence dans la Kabbale.',k:'ein sof lumiere infinie kabbale ohr'},
  {f:'vodou.html',t:'Vodou Haïtien',d:'Le Vodou haïtien, les Lwa, Legba, Ogou, Erzulie, Baron Samdi, Ayizan. Heritage spirituel haïtien.',k:'vodou haitien lwa legba ogou erzulie baron samdi ayizan heritage'},
  {f:'prieres.html',t:'Prières Kabbalistiques',d:'Prières et invocations kabbalistiques — Modeh Ani, Ana Bekoach, Shema, prières du matin et du soir.',k:'prieres kabbalistiques modeh ani ana bekoach shema invocations'},
  {f:'rituels.html',t:'Rituels',d:'Rituels kabbalistiques et haïtiens pour la protection, la purification et l\'élévation.',k:'rituels protection purification elevation kabbale vodou'},
  {f:'rituels-nivo1.html',t:'Rituels Niveau 1',d:'Premiers rituels pour les étudiants débutants — purification et ancrage.',k:'rituels niveau debutant purification ancrage'},
  {f:'meditation-lettre.html',t:'Méditation sur les Lettres',d:'Méditation kabbalistique sur les 22 lettres hébraïques et leur énergie.',k:'meditation lettres hebraiques kabbale energie'},
  {f:'leson.html',t:'Leçons',d:'Les leçons fondamentales de l\'Académie Bnei Ohr — enseignements kabbalistiques.',k:'lecons enseignements academie kabbale fondements'},
  {f:'presentation.html',t:'Présentation de Bnei Ohr',d:'L\'école ésotérique haïtienne Bnei Ohr — sa mission, sa vision, ses fondements.',k:'presentation ecole esoterisme mission vision fondements'},
  {f:'klippot.html',t:'Les Klippot',d:'Les Klippot — forces d\'impureté et d\'obstruction dans la Kabbale.',k:'klippot impurete obstruction kabbale forces'},
  {f:'mal-klippot.html',t:'Mal et Klippot',d:'Le mal, les forces obscures et les Klippot dans la pensée kabbalistique.',k:'mal klippot forces obscures kabbale'},
  {f:'tikkun-olam.html',t:'Tikkun Olam',d:'Tikkun Olam — la réparation du monde, concept central de la Kabbale.',k:'tikkun olam reparation monde kabbale'},
  {f:'kabbalah-chretienne.html',t:'Kabbale & Christianisme',d:'Les liens entre la Kabbale et le Christianisme — traditions ésotériques comparées.',k:'kabbale christianisme traditions esoteriques'},
  {f:'astrologie-kabbalistique-fr.html',t:'Astrologie Kabbalistique',d:'L\'astrologie dans la tradition kabbalistique — planètes, Sefirot et correspondances.',k:'astrologie kabbalistique planetes sefirot correspondances'},
  {f:'ibbur-dibbuk-fr.html',t:'Ibbur et Dibbuk',d:'Les âmes errantes dans la tradition kabbalistique — Ibbur et Dibbuk.',k:'ibbur dibbuk ames errantes kabbale tradition'},
  {f:'mezouza-fr.html',t:'La Mezouza',d:'La Mezouza — protection divine et symbolisme dans la Kabbale.',k:'mezouza protection divine symbolisme kabbale'},
  {f:'ntg-fr.html',t:'Nom de Dieu',d:'Les noms divins dans la Kabbale — YHVH, Elohim, Shaddai et leur puissance.',k:'noms divins yhvh elohim shaddai kabbale puissance'},
  {f:'pont-haiti-fr.html',t:'Pont Haïti',d:'Le pont entre la Kabbale et les traditions haïtiennes — synthèse spirituelle.',k:'pont haiti kabbale vodou synthese spirituelle'},
  {f:'segoula-fr.html',t:'Ségoula',d:'Les Ségoula — pratiques kabbalistiques de protection et d\'élévation spirituelle.',k:'segoula pratiques kabbalistiques protection elevation'},
  {f:'lougarou.html',t:'Lougarou',d:'Le Lougarou dans la tradition haïtienne — mythe, symbolisme et dimension ésotérique.',k:'lougarou tradition haitienne mythe symbolisme'},
  {f:'glosye.html',t:'Glossaire',d:'Glossaire des termes kabbalistiques et vodou — définitions et explications.',k:'glossaire termes kabbale vodou definitions'},
  {f:'goral.html',t:'Goral',d:'Le Goral — divination dans la tradition kabbalistique.',k:'goral divination kabbale tradition'},
  {f:'kamea.html',t:'Kamea',d:'Les Kamea — talismans et carrés magiques dans la Kabbale.',k:'kamea talismans carres magiques kabbale'},
  {f:'ayiti.html',t:'Haïti Spirituelle',d:'La dimension spirituelle d\'Haïti — heritage, traditions et identité profonde.',k:'haiti spirituelle heritage traditions identite'},
  {f:'initiation.html',t:'Initiation',d:'Le chemin initiatique dans l\'école Bnei Ohr — niveaux et progression.',k:'initiation chemin niveaux progression esoterisme'},
  {f:'psaumes.html',t:'Psaumes',d:'Psaumes hébraïques — textes sacrés et leur application spirituelle.',k:'psaumes hebraiques sacres spirituel priere'},
  {f:'lecon-1-fr.html',t:'Leçon 1 — Fondements',d:'Première leçon — introduction à la Kabbale et à l\'Arbre de Vie.',k:'lecon 1 fondements kabbale arbre vie introduction'},
  {f:'lecon-2-fr.html',t:'Leçon 2 — Les Sefirot',d:'Deuxième leçon — étude approfondie des Sefirot et leurs correspondances.',k:'lecon 2 sefirot correspondances etude'},
  {f:'lecon-3-fr.html',t:'Leçon 3 — Les Lettres',d:'Troisième leçon — les 22 lettres hébraïques et la Guématria.',k:'lecon 3 lettres hebraiques guematria'},
  {f:'lecon-4-fr.html',t:'Leçon 4 — Pratiques',d:'Quatrième leçon — pratiques méditatives et rituelles de la Kabbale.',k:'lecon 4 pratiques meditation rituels'},
  {f:'rit-4directions.html',t:'Rituel des 4 Directions',d:'Rituel kabbalistique des quatre directions — protection et ancrage.',k:'rituel 4 directions protection ancrage kabbale'},
  {f:'rit-croix-kabal.html',t:'Rituel de la Croix',d:'Rituel de la croix kabbalistique — purification et protection.',k:'rituel croix kabbalistique purification protection'},
  {f:'rit-modeh-ani.html',t:'Modeh Ani',d:'La prière Modeh Ani — action de grâce du matin dans la tradition kabbalistique.',k:'modeh ani priere matin grace kabbale'},
  {f:'rit-netilat.html',t:'Netilat Yadaïm',d:'Le rituel du lavage des mains — Netilat Yadaïm dans la tradition kabbalistique.',k:'netilat yadaim lavage mains rituel kabbale'},
  {f:'rit-protection.html',t:'Rituel de Protection',d:'Rituel kabbalistique de protection — bouclier de lumière divine.',k:'rituel protection lumiere divine kabbale bouclier'},
  {f:'rit-shabbat.html',t:'Shabbat',d:'Les rituels du Shabbat dans la tradition kabbalistique — sanctification et lumière.',k:'shabbat rituel kabbale sanctification lumiere'},
  {f:'rit-soir.html',t:'Prière du Soir',d:'La prière du soir dans la tradition kabbalistique — Shema Israël.',k:'priere soir shema israel kabbale'},
  {f:'reflexion-ein-od-milvado.html',t:'Réflexion — Ein Od Milvado',d:'Réflexion profonde sur Ein Od Milvado — il n\'y a rien d\'autre que Lui.',k:'reflexion ein od milvado il ny a rien autre'},
  {f:'reflexion-kabbalah-belle.html',t:'Réflexion Kabbale',d:'Réflexion sur la beauté de la Kabbale et son enseignement profond.',k:'reflexion kabbale beaute enseignement'},
  {f:'reflexion-loi-miroir.html',t:'Loi du Miroir',d:'Réflexion sur la loi du miroir — tout ce que tu vois en l\'autre est en toi.',k:'loi miroir reflexion interieur projection'},
  {f:'trois-rayons.html',t:'Les Trois Rayons',d:'Les trois rayons de l\'enseignement Bnei Ohr — Kabbale, Vodou, Hermétisme.',k:'trois rayons kabbale vodou hermetisme enseignement'},
  {f:'ohr.html',t:'La Lumière — Ohr',d:'La lumière dans la Kabbale — Ohr Ein Sof, lumière infinie et création.',k:'lumiere ohr kabbale creation infini'},
  {f:'bibliyotek.html',t:'Bibliothèque',d:'Bibliothèque de ressources spirituelles — livres, textes et références kabbalistiques.',k:'bibliotheque ressources livres textes kabbale'},
  {f:'cercle.html',t:'Le Cercle',d:'Le Cercle d\'étude Bnei Ohr — communauté et pratique collective.',k:'cercle etude communaute pratique'},
  {f:'apropos.html',t:'À Propos',d:'À propos de l\'Académie Bnei Ohr — fondateur, mission et vision spirituelle.',k:'a propos academie fondateur mission vision'},
];
